import type { CompetitionData, Match, MatchEvent, Player, Team } from "./types";

export const teams: Team[] = [
  { id: "access-bank", name: "Access Bank FC", logoUrl: null },
  { id: "zenith-bank", name: "Zenith Bank FC", logoUrl: null },
  { id: "gtbank", name: "GTBank United", logoUrl: null },
  { id: "first-bank", name: "First Bank Lions", logoUrl: null },
  { id: "uba", name: "UBA Warriors", logoUrl: null },
  { id: "fidelity-bank", name: "Fidelity Stars", logoUrl: null },
  { id: "stanbic-ibtc", name: "Stanbic IBTC FC", logoUrl: null },
  { id: "sterling-bank", name: "Sterling Strikers", logoUrl: null },
  { id: "wema-bank", name: "Wema Bank FC", logoUrl: null },
  { id: "keystone-bank", name: "Keystone Rovers", logoUrl: null },
  { id: "union-bank", name: "Union Bank FC", logoUrl: null },
  { id: "fcmb", name: "FCMB Eagles", logoUrl: null },
  { id: "ecobank", name: "Ecobank Royals", logoUrl: null },
  { id: "polaris-bank", name: "Polaris Bank FC", logoUrl: null },
];

export const players: Player[] = [
  { id: "p-access-1", teamId: "access-bank", name: "Tunde Akinwale", position: "Forward", jerseyNumber: 9 },
  { id: "p-access-2", teamId: "access-bank", name: "Chinedu Okafor", position: "Midfielder", jerseyNumber: 10 },
  { id: "p-zenith-1", teamId: "zenith-bank", name: "Musa Bello", position: "Forward", jerseyNumber: 11 },
  { id: "p-zenith-2", teamId: "zenith-bank", name: "Emeka Nwosu", position: "Goalkeeper", jerseyNumber: 1 },
  { id: "p-gtbank-1", teamId: "gtbank", name: "Femi Adeyemi", position: "Forward", jerseyNumber: 7 },
  { id: "p-gtbank-2", teamId: "gtbank", name: "Daniel Etim", position: "Defender", jerseyNumber: 5 },
  { id: "p-first-1", teamId: "first-bank", name: "Kunle Bakare", position: "Midfielder", jerseyNumber: 8 },
  { id: "p-first-2", teamId: "first-bank", name: "Ifeanyi Obi", position: "Forward", jerseyNumber: 14 },
  { id: "p-uba-1", teamId: "uba", name: "Seyi Lawal", position: "Forward", jerseyNumber: 17 },
  { id: "p-uba-2", teamId: "uba", name: "Victor Eze", position: "Defender", jerseyNumber: 4 },
  { id: "p-fidelity-1", teamId: "fidelity-bank", name: "Jude Hassan", position: "Forward", jerseyNumber: 19 },
  { id: "p-fidelity-2", teamId: "fidelity-bank", name: "Nnamdi Cole", position: "Goalkeeper", jerseyNumber: 22 },
  { id: "p-stanbic-1", teamId: "stanbic-ibtc", name: "Peter Danjuma", position: "Midfielder", jerseyNumber: 6 },
  { id: "p-stanbic-2", teamId: "stanbic-ibtc", name: "Ahmed Sani", position: "Forward", jerseyNumber: 12 },
  { id: "p-sterling-1", teamId: "sterling-bank", name: "Bayo Thomas", position: "Forward", jerseyNumber: 21 },
  { id: "p-sterling-2", teamId: "sterling-bank", name: "Henry Ojo", position: "Defender", jerseyNumber: 2 },
  { id: "p-wema-1", teamId: "wema-bank", name: "Samuel Kalu", position: "Midfielder", jerseyNumber: 16 },
  { id: "p-wema-2", teamId: "wema-bank", name: "David Musa", position: "Forward", jerseyNumber: 20 },
  { id: "p-keystone-1", teamId: "keystone-bank", name: "Kelvin Ajayi", position: "Forward", jerseyNumber: 13 },
  { id: "p-keystone-2", teamId: "keystone-bank", name: "Paul Yusuf", position: "Goalkeeper", jerseyNumber: 33 },
  { id: "p-union-1", teamId: "union-bank", name: "Dennis Uche", position: "Midfielder", jerseyNumber: 18 },
  { id: "p-union-2", teamId: "union-bank", name: "Kola Martins", position: "Defender", jerseyNumber: 3 },
  { id: "p-fcmb-1", teamId: "fcmb", name: "Michael Odili", position: "Forward", jerseyNumber: 15 },
  { id: "p-fcmb-2", teamId: "fcmb", name: "Ayo Ekanem", position: "Goalkeeper", jerseyNumber: 30 },
  { id: "p-eco-1", teamId: "ecobank", name: "George Mensah", position: "Forward", jerseyNumber: 23 },
  { id: "p-eco-2", teamId: "ecobank", name: "Francis Udom", position: "Midfielder", jerseyNumber: 24 },
  { id: "p-polaris-1", teamId: "polaris-bank", name: "Abel Osagie", position: "Forward", jerseyNumber: 27 },
  { id: "p-polaris-2", teamId: "polaris-bank", name: "Wale Johnson", position: "Defender", jerseyNumber: 28 },
];

export const matches: Match[] = [
  {
    id: "match-1",
    stage: "group",
    homeTeamId: "access-bank",
    awayTeamId: "zenith-bank",
    kickoff: "2026-09-13T15:00:00+01:00",
    venue: "Legacy Pitch",
    status: "completed",
    homeScore: 2,
    awayScore: 1,
  },
  {
    id: "match-2",
    stage: "group",
    homeTeamId: "gtbank",
    awayTeamId: "first-bank",
    kickoff: "2026-09-13T16:30:00+01:00",
    venue: "Legacy Pitch",
    status: "completed",
    homeScore: 0,
    awayScore: 0,
  },
  {
    id: "match-3",
    stage: "group",
    homeTeamId: "uba",
    awayTeamId: "fidelity-bank",
    kickoff: "2026-09-14T15:00:00+01:00",
    venue: "Marina Arena",
    status: "completed",
    homeScore: 3,
    awayScore: 2,
  },
  {
    id: "match-4",
    stage: "group",
    homeTeamId: "stanbic-ibtc",
    awayTeamId: "sterling-bank",
    kickoff: "2026-09-14T16:30:00+01:00",
    venue: "Marina Arena",
    status: "completed",
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: "match-5",
    stage: "group",
    homeTeamId: "wema-bank",
    awayTeamId: "keystone-bank",
    kickoff: "2026-09-20T15:00:00+01:00",
    venue: "Union Sports Complex",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "match-6",
    stage: "group",
    homeTeamId: "union-bank",
    awayTeamId: "fcmb",
    kickoff: "2026-09-20T16:30:00+01:00",
    venue: "Union Sports Complex",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "match-7",
    stage: "group",
    homeTeamId: "ecobank",
    awayTeamId: "polaris-bank",
    kickoff: "2026-09-21T15:00:00+01:00",
    venue: "Legacy Pitch",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "match-8",
    stage: "quarter_final",
    homeTeamId: "access-bank",
    awayTeamId: "first-bank",
    kickoff: "2026-10-17T15:00:00+01:00",
    venue: "Finals Arena",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
    homePenaltyScore: null,
    awayPenaltyScore: null,
    winnerTeamId: null,
  },
];

export const events: MatchEvent[] = [
  {
    id: "event-1",
    matchId: "match-1",
    teamId: "access-bank",
    playerId: "p-access-1",
    assistPlayerId: "p-access-2",
    type: "goal",
    half: 1,
    minute: 18,
    addedTime: 0,
  },
  {
    id: "event-2",
    matchId: "match-1",
    teamId: "zenith-bank",
    playerId: "p-zenith-1",
    assistPlayerId: null,
    type: "goal",
    half: 2,
    minute: 44,
    addedTime: 0,
  },
  {
    id: "event-3",
    matchId: "match-1",
    teamId: "access-bank",
    playerId: "p-access-1",
    assistPlayerId: "p-access-2",
    type: "goal",
    half: 2,
    minute: 60,
    addedTime: 2,
  },
  {
    id: "event-4",
    matchId: "match-3",
    teamId: "uba",
    playerId: "p-uba-1",
    assistPlayerId: null,
    type: "goal",
    half: 1,
    minute: 12,
    addedTime: 0,
  },
  {
    id: "event-5",
    matchId: "match-3",
    teamId: "fidelity-bank",
    playerId: "p-fidelity-1",
    assistPlayerId: null,
    type: "goal",
    half: 1,
    minute: 30,
    addedTime: 1,
  },
  {
    id: "event-6",
    matchId: "match-3",
    teamId: "uba",
    playerId: "p-uba-1",
    assistPlayerId: "p-uba-2",
    type: "goal",
    half: 2,
    minute: 39,
    addedTime: 0,
  },
  {
    id: "event-7",
    matchId: "match-3",
    teamId: "fidelity-bank",
    playerId: "p-fidelity-1",
    assistPlayerId: null,
    type: "goal",
    half: 2,
    minute: 58,
    addedTime: 0,
  },
  {
    id: "event-8",
    matchId: "match-3",
    teamId: "uba",
    playerId: "p-uba-1",
    assistPlayerId: "p-uba-2",
    type: "goal",
    half: 2,
    minute: 60,
    addedTime: 1,
  },
  {
    id: "event-9",
    matchId: "match-4",
    teamId: "stanbic-ibtc",
    playerId: "p-stanbic-2",
    assistPlayerId: "p-stanbic-1",
    type: "goal",
    half: 2,
    minute: 51,
    addedTime: 0,
  },
  {
    id: "event-10",
    matchId: "match-4",
    teamId: "sterling-bank",
    playerId: "p-sterling-1",
    assistPlayerId: null,
    type: "goal",
    half: 2,
    minute: 60,
    addedTime: 3,
  },
  {
    id: "event-11",
    matchId: "match-1",
    teamId: "zenith-bank",
    playerId: "p-zenith-1",
    type: "yellow_card",
    half: 2,
    minute: 49,
    addedTime: 0,
  },
  {
    id: "event-12",
    matchId: "match-3",
    teamId: "fidelity-bank",
    playerId: "p-fidelity-1",
    type: "red_card",
    half: 2,
    minute: 60,
    addedTime: 4,
  },
];

export const demoCompetition: CompetitionData = {
  teams,
  players,
  matches,
  events,
  penalties: [],
  source: "demo",
};
